name: Update Translations
on:
  workflow_dispatch:
  push:
    paths:
    - '.github/workflows/update-translations.yml'
    - 'scripts/update.sh'
  schedule:
    - cron:  '0 4,16 * * *'
jobs:
  update-translations:
    runs-on: ubuntu-latest
    if: github.repository == 'wpilibsuite/frc-docs-translations'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'true'
      - name: Update Submodule
        run: |
          git submodule update --recursive --remote
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Update wheel
        run: |
          pip install wheel==0.34.2
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: Update Translations
        run: |
          sh scripts/update.sh
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
      - name: Lock Unused Transifex Resources
        run: |
          python scripts/lock-translations.py .tx/config
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
      - name: Create Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Translations from Transifex"
          commit_user_name: GitHub
          commit_user_email: noreply@github.com
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
