name: Update po/pot files

env:
  # branch name of python-docs-ja repository
  DOCS_BRANCH: "3.10"
  # branch name of cpython repository
  CPYTHON_BRANCH: "3.10"
  # branch name of cpython-doc-catalog repository
  CATALOG_BRANCH: "catalog-3.10"
  # Transifex project name
  TRANSIFEX_PROJECT: "python-newest"

on: workflow_dispatch
  # schedule:
  #  - cron: "0 9 * * *"

jobs:

  Org-Preparation:
    runs-on: ubuntu-latest

    steps:
      - name: Check out python-docs-ja
        uses: actions/checkout@v2
      
      - name: Test checkout
        run: |
          pwd
          echo ${GITHUB_WORKSPACE}
        
        
      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: "3.10"
          architecture: "x64"
          
      - name: Install packages
        run: |
          pip install --upgrade sphinx
          pip install --upgrade sphinx-intl
          pip install --upgrade blurb
          pip install --upgrade transifex-client
          
      - name: Setup tx
        run: |
          mv "${GITHUB_WORKSPACE}/.github/files/.transifexrc" ~/.transifexrc
          cd ~
          cat .transifexrc
        
          
  Upload-Catalog:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out cpython-doc-catalog
        run: |
          echo ${GITHUB_WORKSPACE}
          cd "${GITHUB_WORKSPACE}"
          git clone --branch main git@github.com:python-doc-ja/cpython-doc-catalog.git
          mkdir -p "${GITHUB_WORKSPACE}"/cpython-doc-catalog/Doc/locales/ja
          cd "${GITHUB_WORKSPACE}"/cpython-doc-catalog/Doc/locales/ja
          ln -s "${GITHUB_WORKSPACE}"/python-docs-ja LC_MESSAGES
          ls -lF LC_MESSAGES
          

  Renew-Upload-Catalog:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
   
          

      
